"""Vietnamese PII detection helpers for MedViet Lab 24.

The README asks for Presidio custom recognizers. This module keeps Presidio's
RecognizerResult output format, but uses deterministic regex/rule recognizers so
it still works in local lab environments where the Vietnamese spaCy model is not
available yet.
"""
from __future__ import annotations

import re
from dataclasses import dataclass, field
from typing import Iterable

from presidio_analyzer import Pattern, PatternRecognizer, RecognizerResult

CCCD_RE = re.compile(r"(?<!\d)\d{12}(?!\d)")
# Accept both normal VN phone numbers and values whose leading zero was stripped
# by pandas CSV type inference.
PHONE_RE = re.compile(r"(?<!\d)(?:0[35789]\d{8}|[35789]\d{8})(?!\d)")
EMAIL_RE = re.compile(r"(?i)\b[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}\b")
# Vietnamese/ASCII capitalized names, including short last initials such as "A".
NAME_RE = re.compile(
    r"\b[A-ZÀÁẠẢÃÂẦẤẬẨẪĂẰẮẶẲẴÈÉẸẺẼÊỀẾỆỂỄÌÍỊỈĨÒÓỌỎÕÔỒỐỘỔỖƠỜỚỢỞỠÙÚỤỦŨƯỪỨỰỬỮỲÝỴỶỸĐ]"
    r"[a-zàáạảãâầấậẩẫăằắặẳẵèéẹẻẽêềếệểễìíịỉĩòóọỏõôồốộổỗơờớợởỡùúụủũưừứựửữỳýỵỷỹđ]+"
    r"(?:\s+[A-ZÀÁẠẢÃÂẦẤẬẨẪĂẰẮẶẲẴÈÉẸẺẼÊỀẾỆỂỄÌÍỊỈĨÒÓỌỎÕÔỒỐỘỔỖƠỜỚỢỞỠÙÚỤỦŨƯỪỨỰỬỮỲÝỴỶỸĐ]"
    r"(?:[a-zàáạảãâầấậẩẫăằắặẳẵèéẹẻẽêềếệểễìíịỉĩòóọỏõôồốộổỗơờớợởỡùúụủũưừứựửữỳýỵỷỹđ]+|\.?)"
    r"){1,4}\b"
)

DEFAULT_ENTITIES = ["PERSON", "EMAIL_ADDRESS", "VN_CCCD", "VN_PHONE"]


@dataclass
class _RecognizerRegistry:
    recognizers: list[object] = field(default_factory=list)

    def add_recognizer(self, recognizer: object) -> None:
        self.recognizers.append(recognizer)


class VietnameseAnalyzer:
    """Small analyzer with the same `.analyze()` surface used in the lab tests."""

    def __init__(self) -> None:
        self.registry = _RecognizerRegistry()

    def analyze(
        self,
        text: str,
        language: str = "vi",
        entities: Iterable[str] | None = None,
        **_: object,
    ) -> list[RecognizerResult]:
        del language  # Regex rules are language-independent for this lab.
        wanted = set(entities or DEFAULT_ENTITIES)
        text = "" if text is None else str(text)
        results: list[RecognizerResult] = []

        if "EMAIL_ADDRESS" in wanted:
            results.extend(_regex_results(text, EMAIL_RE, "EMAIL_ADDRESS", 0.95))
        if "VN_CCCD" in wanted:
            results.extend(_regex_results(text, CCCD_RE, "VN_CCCD", 0.90))
        if "VN_PHONE" in wanted:
            results.extend(_regex_results(text, PHONE_RE, "VN_PHONE", 0.88))
        if "PERSON" in wanted:
            results.extend(_detect_person(text))

        return _dedupe_and_sort(results)


def _regex_results(text: str, pattern: re.Pattern[str], entity_type: str, score: float) -> list[RecognizerResult]:
    return [RecognizerResult(entity_type=entity_type, start=m.start(), end=m.end(), score=score) for m in pattern.finditer(text)]


def _detect_person(text: str) -> list[RecognizerResult]:
    # Names generated by Faker("vi_VN") are often standalone strings. This
    # heuristic intentionally avoids strings with digits, email symbols, or CSV
    # punctuation that look more like addresses than person names.
    stripped = text.strip()
    if not stripped or any(ch.isdigit() for ch in stripped) or "@" in stripped:
        return []

    results: list[RecognizerResult] = []
    for match in NAME_RE.finditer(text):
        candidate = match.group(0).strip()
        lowered = candidate.lower()
        # Avoid common false positives from labels or medical conditions.
        if lowered in {"bệnh nhân", "huyết áp", "tiểu đường", "tim mạch", "khỏe mạnh"}:
            continue
        if len(candidate.split()) >= 2:
            results.append(RecognizerResult(entity_type="PERSON", start=match.start(), end=match.end(), score=0.78))

    # If a full cell is a lower-noise two-to-six-word name, mark the whole cell.
    tokens = stripped.split()
    if not results and 2 <= len(tokens) <= 6 and all(re.search(r"[A-Za-zÀ-ỹĐđ]", t) for t in tokens):
        results.append(RecognizerResult(entity_type="PERSON", start=0, end=len(text), score=0.75))
    return results


def _dedupe_and_sort(results: list[RecognizerResult]) -> list[RecognizerResult]:
    seen: set[tuple[str, int, int]] = set()
    unique: list[RecognizerResult] = []
    for result in sorted(results, key=lambda r: (r.start, -(r.end - r.start), r.entity_type)):
        key = (result.entity_type, result.start, result.end)
        if key not in seen:
            seen.add(key)
            unique.append(result)
    return unique


def build_vietnamese_analyzer() -> VietnameseAnalyzer:
    """Build analyzer and register the custom recognizers requested by the README."""
    cccd_pattern = Pattern(name="cccd_pattern", regex=CCCD_RE.pattern, score=0.90)
    cccd_recognizer = PatternRecognizer(
        supported_entity="VN_CCCD",
        patterns=[cccd_pattern],
        context=["cccd", "căn cước", "chứng minh", "cmnd"],
    )

    phone_pattern = Pattern(name="vn_phone", regex=PHONE_RE.pattern, score=0.88)
    phone_recognizer = PatternRecognizer(
        supported_entity="VN_PHONE",
        patterns=[phone_pattern],
        context=["điện thoại", "sdt", "phone", "liên hệ"],
    )

    analyzer = VietnameseAnalyzer()
    analyzer.registry.add_recognizer(cccd_recognizer)
    analyzer.registry.add_recognizer(phone_recognizer)
    return analyzer


def detect_pii(text: str, analyzer: VietnameseAnalyzer | None = None) -> list[RecognizerResult]:
    """Detect PII in Vietnamese text.

    Returns Presidio RecognizerResult objects for PERSON, EMAIL_ADDRESS,
    VN_CCCD, and VN_PHONE.
    """
    analyzer = analyzer or build_vietnamese_analyzer()
    return analyzer.analyze(text=str(text), language="vi", entities=DEFAULT_ENTITIES)
